trigger:
- main

pool: Agent-ka-boss

jobs:
- job: terraform
  displayName: terraform commands
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'MyApp-ServicePrincipal'
    backendAzureRmResourceGroupName: 'tfstate-rg'
    backendAzureRmStorageAccountName: 'tfstatestorage5'
    backendAzureRmContainerName: 'tfstatecontainer'
    backendAzureRmKey: 'terraform.tfstate'
- job: terraformplan
  displayName: terraform plan
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'MyApp-ServicePrincipal'
- job: manualvalidation
  displayName: Manual validation
  pool: server
- task: ManualValidation@1
  inputs:
    notifyUsers: 'kulshrshth8'
    approvers: 'kulshrshth8@gmail.com'