trigger: none

pool: New-Group-Agent

stages:
  - stage: TerraformInit
    displayName: Terraform Initialization
    jobs:
      - job: InitJob
        displayName: Run terraform init
        continueOnError: true
        workspace:
          clean: outputs
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'MyApp-ServicePrincipal'
              backendAzureRmStorageAccountName: 'rgstorage90'
              backendAzureRmContainerName: '$logs'
              backendAzureRmKey: 'terraform.tfstate'

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)/.terraform'
              artifact: 'terraform-init'
              publishLocation: 'pipeline'

  - stage: TerraformValidate
    displayName: Terraform Validation
    dependsOn: TerraformInit
    jobs:
      - job: ValidateJob
        displayName: Run terraform validate
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              artifact: 'terraform-init'
              path: '$(System.DefaultWorkingDirectory)/.terraform'

          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'validate'

  - stage: TerraformPlan
    displayName: Terraform Plan
    dependsOn: TerraformValidate
    jobs:
      - job: PlanJob
        displayName: Run terraform plan
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              artifact: 'terraform-init'
              path: '$(System.DefaultWorkingDirectory)/.terraform'

          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'MyApp-ServicePrincipal'
