trigger: none

pool: New-Group-Agent

variables:
  terraformWorkingDir: '$(System.DefaultWorkingDirectory)'

stages:
  - stage: TerraformInit
    displayName: Terraform Init
    jobs:
      - job: InitJob
        displayName: Terraform Init
        steps:
          - checkout: self

          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(terraformWorkingDir)'
              backendServiceArm: 'MyApp-ServicePrincipal'
              backendAzureRmStorageAccountName: 'rgstorage90'
              backendAzureRmContainerName: '$logs'
              backendAzureRmKey: 'terraform.tfstate'

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(terraformWorkingDir)'
              artifact: 'terraform-init'

  - stage: TerraformValidate
    displayName: Terraform Validate
    dependsOn: TerraformInit
    jobs:
      - job: ValidateJob
        displayName: Terraform Validate
        steps:
          - checkout: self

          - task: DownloadPipelineArtifact@2
            inputs:
              artifact: 'terraform-init'
              path: '$(terraformWorkingDir)'

          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: '$(terraformWorkingDir)'

  - stage: TerraformPlan
    displayName: Terraform Plan
    dependsOn: TerraformValidate
    jobs:
      - job: PlanJob
        displayName: Terraform Plan
        steps:
          - checkout: self

          - task: DownloadPipelineArtifact@2
            inputs:
              artifact: 'terraform-init'
              path: '$(terraformWorkingDir)'

          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(terraformWorkingDir)'
              environmentServiceNameAzureRM: 'MyApp-ServicePrincipal'
