trigger: none
pool: New-Group-Agent
jobs:
  - job: job1
  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'init'
      backendServiceArm: 'MyApp-ServicePrincipal'
      backendAzureRmStorageAccountName: 'uhr'
      backendAzureRmContainerName: 'zse'
      backendAzureRmKey: 'terrafaom.tf.state'
  - job: job2
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'validate'
        
